image:
  file: .devcontainer/Dockerfile
  context: .devcontainer
ports:
  - port: 4000
  - port: 35729
vscode:
  extensions:
    - erlang-ls.erlang-ls
tasks:
  - name: Init
    command: .devcontainer/post-create.sh
  - name: Static Server
    command: make serve
