image:
  file: .devcontainer/Dockerfile
  context: .devcontainer
ports:
  - port: 4000
  - port: 35729
vscode:
  extensions:
    - erlang-ls.erlang-ls
tasks:
  - name: Static Server
    init: .devcontainer/post-create.sh
    command: make serve
