url: "https://erlang.org" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Erlang/OTP" # the name of your site, e.g. ACME Corp.

collections:
  news:
    output: true
    permalink: /:collection/:path
    sort_by: id

sass:
  style: compressed
  load_paths:
    - _sass
    - node_modules

include:
  - node_modules
exclude:
  - LICENSE
  - Makefile
  - README.md
  - package.json
  - package-lock.json

kramdown:
  input: GFM