url: "https://erlang.org" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site
title: "Erlang/OTP" # the name of your site, e.g. ACME Corp.
description: "The official home of the Erlang Programming Language"

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-liquify
  - jekyll-commonmark

collections:
  news:
    output: true
    permalink: /:collection/:path
    sort_by: date
  releases:
    output: true
    permalink: /downloads/:path
    sort_by: release
  patches:
    output: true
    permalink: /:collection/:path
    sort_by: tag_name
  posts:
    output: true
    permalink: /blog/:title/
  eeps:
    output: true
    permalink: /:collection/:path

feed:
  collections:
    news:
      path: "/news.xml"
    posts:
      path: "/blog.xml"

sass:
  style: compressed
  load_paths:
    - _sass
    - node_modules

exclude:
  - LICENSE
  - Makefile
  - README.md
  - package.json
  - package-lock.json
  - tsconfig.json
  - otp_versions.table
  - Gemfile*
  - _scripts/
  - _clones/
  - _news/README.md
  - _posts/README.md
  - _releases/README.md
  - docsearch.json

markdown: CommonMark

commonmark:
  options: ["SMART", "FOOTNOTES", "UNSAFE"]
  extensions: ["strikethrough", "autolink", "table"]
