version: '3.1'

services:

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_PASSWORD: postgres

  erlang-org:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
