name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - uses: actions/setup-node@v2
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install npx
        run: npm i -g npx
      - name: Fetch otp_versions.table
        run: make otp_versions.table
      - name: Cache Erlang docs modules
        id: docs-cache
        uses: actions/cache@v2
        with:
          path: |
            doc
            docs
          key: ${{ runner.os }}-${{ hashFiles('**/otp_versions.table', '_scripts/otp_flatten_docs', '_scripts/download-docs.sh') }}
      - name: Touch docs for makefile
        if: steps.docs-cache.outputs.cache-hit == 'true'
        run: touch docs
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '>23'
          rebar3-version: '3'
      
      - name: Install ubuntu packages
        run: |
          sudo apt update -y 
          sudo apt install xsltproc -y

      - name: Check Site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ secrets.URL }}
        run: make check

      - name: Install and Build 🔧
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ secrets.URL }}
        run: |
          URL=${URL:-"https://${{ github.repository_owner }}.github.io"}
          sed -i "s@url: \"https://erlang.org\"@url: \"${URL}\"@g" _config.yml
          REPOSITORY_NAME=$(echo ${{ github.repository }} | tr '/' ' ' | awk '{ print $2 }')
          sed -i "s@baseurl: \"\"@baseurl: \"/$REPOSITORY_NAME\"@g" _config.yml
          make build
          touch _site/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: _site # The folder the action should deploy.
          single-commit: true
