name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - uses: actions/setup-node@v2
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('package-lock.json') }}
      - name: Fetch otp_versions.table
        run: make otp_versions.table
      - name: Cache Erlang docs modules
        id: docs-cache
        uses: actions/cache@v2
        with:
          path: |
            doc
            docs
          key: ${{ runner.os }}-${{ hashFiles('_scripts/otp_flatten_docs', '_scripts/download-docs.sh', '_scripts/otp_doc_sitemap') }}
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - uses: erlef/setup-beam@v1
        with:
          otp-version: '>23'
          rebar3-version: '3'

      - name: Install ubuntu packages
        run: |
          sudo apt update -y
          sudo apt install xsltproc yamllint -y

      - name: Lint Site 🧪
        run: make lint

      - name: Configure Site 📈
        run: |
          if [ "${{ github.repository }}" = "erlang/erlang-org" ]; then
            URL="beta.erlang.org"
            REPOSITORY_NAME=
          else
            URL="${{ github.repository_owner }}.github.io"
            REPOSITORY_NAME=$(echo ${{ github.repository }} | tr '/' ' ' | awk '{ print "/" $2 }')
          fi
          sed -i "s@url: \"https://erlang.org\"@url: \"https://${URL}\"@g" _config.yml
          sed -i "s@baseurl: \"\"@baseurl: \"$REPOSITORY_NAME\"@g" _config.yml
          echo ${URL} > CNAME

      - name: Setup site 💽
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make -j4 setup

      - name: Check Site 🧪
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make check

      - name: Install and Build 🔧
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make build
          touch _site/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: _site # The folder the action should deploy.
          single-commit: true
      # Sleep for 5 minutes to allow gh-pages to deploy
      # then we re-index the docs. Need to export APP_ID and API_KEY to work.
      # - name: Re-index algolia
      #   run: |
      #     sleep 300
      #     make algolia
