name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          sed -i 's@https://erlang.org@https://${{ github.repository_owner }}.github.io@g' _config.yml
          REPOSITORY_NAME=$(echo ${{ github.repository }} | tr '/' ' ' | awk '{ print $2 }')
          sed -i "s@baseurl: \"\"@baseurl: \"@REPOSITORY_NAME\"@g" _config.yml
          make export

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: _site # The folder the action should deploy.
